#!/bin/sh
#
# @name Saxion M4E TiltRotor
#
# @type Hexarotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC AUX4 channel
# @output AUX5 feed-through of RC AUX5 channel
# @output AUX6 feed-through of RC AUX6 channel

sh /etc/init.d/rc.mc_defaults
sh /etc/init.d/rc.ctrlalloc

if [ $AUTOCNF = yes ]
then

	param set MPC_USE_HTE 0

	param set VM_MASS 2.0
	param set VM_INERTIA_XX 0.01
	param set VM_INERTIA_YY 0.01
	param set VM_INERTIA_ZZ 0.02

	param set CA_AIRFRAME 3
	param set CA_METHOD 0
	param set CA_ACT0_MIN 0.0
	param set CA_ACT1_MIN 0.0
	param set CA_ACT2_MIN 0.0
	param set CA_ACT3_MIN 0.0
	param set CA_ACT4_MIN 0.0
	param set CA_ACT5_MIN 0.0
	param set CA_ACT6_MIN 0.0
	param set CA_ACT7_MIN 0.0
	param set CA_ACT0_MAX 1.0
	param set CA_ACT1_MAX 1.0
	param set CA_ACT2_MAX 1.0
	param set CA_ACT3_MAX 1.0
	param set CA_ACT4_MAX 1.0
	param set CA_ACT5_MAX 1.0
	param set CA_ACT6_MAX 1.0
	param set CA_ACT7_MAX 1.0

	param set CA_ACT8_MIN -1.0
	param set CA_ACT9_MIN -1.0
	param set CA_ACT10_MIN -1.0
	param set CA_ACT11_MIN -1.0
	param set CA_ACT12_MIN -1.0
	param set CA_ACT13_MIN -1.0
	param set CA_ACT14_MIN -1.0
	param set CA_ACT15_MIN -1.0
	param set CA_ACT8_MAX 1.0
	param set CA_ACT9_MAX 1.0
	param set CA_ACT10_MAX 1.0
	param set CA_ACT11_MAX 1.0
	param set CA_ACT12_MAX 1.0
	param set CA_ACT13_MAX 1.0
	param set CA_ACT14_MAX 1.0
	param set CA_ACT15_MAX 1.0


	param set CA_MC_R5_PX 0.0
	param set CA_MC_R5_PY 1.0
	param set CA_MC_R5_CT 8
	param set CA_MC_R5_KM -0.05
	param set CA_MC_R4_PX 0.0
	param set CA_MC_R4_PY -1.0
	param set CA_MC_R4_CT 8
	param set CA_MC_R4_KM 0.05
	param set CA_MC_R3_PX 0.866025
	param set CA_MC_R3_PY -0.5
	param set CA_MC_R3_CT 8
	param set CA_MC_R3_KM -0.05
	param set CA_MC_R2_PX -0.866025
	param set CA_MC_R2_PY 0.5
	param set CA_MC_R2_CT 8
	param set CA_MC_R2_KM 0.05
	param set CA_MC_R1_PX 0.866025
	param set CA_MC_R1_PY 0.5
	param set CA_MC_R1_CT 8
	param set CA_MC_R1_KM 0.05
	param set CA_MC_R0_PX -0.866025
	param set CA_MC_R0_PY -0.5
	param set CA_MC_R0_CT 8
	param set CA_MC_R0_KM -0.05
fi

set MIXER direct
set PWM_OUT 123456

set MIXER_AUX direct
# set PWM_AUX_OUT 123456
